### PR TITLE
Add the French translation

### PR DESCRIPTION
**Pull request by Vsnmrn**
Here is a proposal to translate your app into french.
(Sorry for the first 6 commits, these are errors on my part, but as you can see I finally added only one file)

### CODE REVIEW

**Review by inson1 — APPROVED** [review]
I translated a few strings using google translate and it seems to be fine. It seems to have all the lines it needs. I do not see any problem.

**Comment by Vsnmrn** [comment]
Please let me work for a few more hours and I will add the metadata translations

**Comment by inson1** [comment]
@Vsnmrn btw if you resolved the comment, please set it as resolved
yea, I also forgot to translate the metadata, I should also do that, thanks!

**Comment by Vsnmrn** [comment]
Finally I'm just set this PR as a draft again the time to solve #12

**Comment by Vsnmrn** [comment]
So I think it is -really- good this time.

Don't hesitate to contact me if needed.

**Review by artyommironov — APPROVED** [review]

**Pull request merged**
